services:
  taskmanagerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"  # HTTP
      
