services:
  taskmanagerapi:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManagerApi/Dockerfile
    depends_on:
      - mssql-server
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "numsey#2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
